
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class mySym {
  /* terminals */
  public static final int LTHEN = 23;
  public static final int DIVIDE = 21;
  public static final int CONST = 6;
  public static final int EEQUAL = 25;
  public static final int EQUALS = 29;
  public static final int GEQUAL = 27;
  public static final int INTEGER = 35;
  public static final int LPAREN = 33;
  public static final int SEMI = 14;
  public static final int MINUS = 17;
  public static final int RPAREN = 34;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int IN = 13;
  public static final int OR = 31;
  public static final int COMMA = 18;
  public static final int GTHEN = 28;
  public static final int BEGIN = 2;
  public static final int PLUS = 16;
  public static final int ASSIGN = 15;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int TIMES = 20;
  public static final int COLON = 19;
  public static final int ELSE = 9;
  public static final int LEQUAL = 24;
  public static final int WHILE = 10;
  public static final int NEQUAL = 26;
  public static final int LET = 12;
  public static final int THEN = 8;
  public static final int END = 3;
  public static final int VAR = 5;
  public static final int DO = 11;
  public static final int EXPONENT = 22;
  public static final int IDENTIFIER = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "IDENTIFIER",
  "VAR",
  "CONST",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "LET",
  "IN",
  "SEMI",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "COMMA",
  "COLON",
  "TIMES",
  "DIVIDE",
  "EXPONENT",
  "LTHEN",
  "LEQUAL",
  "EEQUAL",
  "NEQUAL",
  "GEQUAL",
  "GTHEN",
  "EQUALS",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "INTEGER"
  };
}

