#!/usr/bin/env bash
#Compiles and executes
export CLASSPATH=$CLASSPATH:/home/lixxia/repos/csci420/cup/java-cup-11b.jar:/home/lixxia/repos/csci420/cup/java-cup-11b-runtime.jar:.

jflex miniTriangle.jflex

javac TriangleLexer.java

java TriangleLexerTest sample.tri

